# Generated by Django 4.2.2 on 2023-06-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49)),
                ('is_active', models.BooleanField(default=True)),
                ('is_menu', models.BooleanField(default=True)),
            ],
        ),
    ]
