# Generated by Django 4.2.2 on 2023-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='html_file',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
